### ISSUE TITLE
Need a distro-agnostic way of installing node/npm versions

### ISSUE THREAD

**Issue by thecodenomad** [elibs/ebash#112]
Node comes in many lts versions and flavors, should nvm be used? or should there be a mechanism that allows a version pulled directly from upstream?

This will likely need to be a separate dependency install script like there is for go.

**Comment by marshall-mcmullen** [comment]
I like the idea of a `install/npm` approach to this.

**Comment by marshall-mcmullen** [comment]
Closed by https://github.com/elibs/ebash/pull/115
