### ISSUE TITLE
opt_parse: required string arguments

### ISSUE THREAD

**Issue by marshall-mcmullen** [elibs/ebash#24]
opt_parse is amazing. But there's no way to say that a string option is required to be non-empty. You can do this:

```
$(opt_parse ":a")

argcheck a
```

It would be better if this was built-in to opt_parse with some kind of magic character hint. e.g. we use `:` to denote a string, maybe we can use `=` to indicate it takes a string and it must be non-empty.

**Comment by marshall-mcmullen** [comment]
@ericpe @michael-odell any opinion or feedback on this? The easiest change here would be to simply add a check into the `:` option parsing code to make sure not just that an argument was provided but also that it is non-empty. But that could break backwards compatibility where people may expect the current permissive behavior. So the alternative is to add a new type character (e.g. `=`) to denote an option which takes a required non-empty string argument. 

Thoughts? Opinions?

**Comment by marshall-mcmullen** [comment]
I'm going to go with creating a new non-empty type indicator `=`. 

See changes here: https://github.com/elibs/ebash/tree/opt_nonempty_string

**Comment by ericpe** [comment]
Sorry, just saw this.   I think you made the right choice.

**Comment by marshall-mcmullen** [comment]
Fixed by #32
